/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package markbookreporterui.view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import markbookreporterui.Application;
import markbookreporterui.controller.NewMarkbookDialogController;
import markbookreporterui.utils.DialogResult;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author School
 */
public class NewMarkbookDialog extends javax.swing.JDialog {
    protected DialogResult<NewMarkbookDialogBean> dialogResult = new DialogResult();
    protected NewMarkbookDialogController controller;
    /**
     * Creates new form NewMarkbookDialog
     */
    public NewMarkbookDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        controller = new NewMarkbookDialogController();
        controller.registerView(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        newMarkbookDialogBean = new markbookreporterui.view.NewMarkbookDialogBean();
        jLabel1 = new javax.swing.JLabel();
        markbookTitleTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        markBookFilenameTextField = new javax.swing.JTextField();
        selectFileButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        markBookCurriculumComboBox = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        canelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Markbook");

        jLabel1.setText("Title:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, newMarkbookDialogBean, org.jdesktop.beansbinding.ELProperty.create("${markBookTitle}"), markbookTitleTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel2.setText("Markbook File:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, newMarkbookDialogBean, org.jdesktop.beansbinding.ELProperty.create("${markBookFileLocation}"), markBookFilenameTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        selectFileButton.setText("Browse");
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Curriculum:");

        markBookCurriculumComboBox.setModel(new DefaultComboBoxModel(Application.getInstance().getCurriculumTitles().toArray()));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, newMarkbookDialogBean, org.jdesktop.beansbinding.ELProperty.create("${curriculumTitle}"), markBookCurriculumComboBox, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        canelButton.setText("Cancel");
        canelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markbookTitleTextField)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(markBookCurriculumComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 218, Short.MAX_VALUE)
                            .addComponent(markBookFilenameTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectFileButton)
                        .addGap(8, 8, 8))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(markbookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(markBookFilenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(markBookCurriculumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(canelButton))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Microsoft Excel 2000 Files", "xls");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                newMarkbookDialogBean.setMarkBookFile(chooser.getSelectedFile());
                newMarkbookDialogBean.setMarkBookFileLocation(newMarkbookDialogBean.getMarkBookFile().getCanonicalPath());
            } catch (IOException ex) {
                Logger.getLogger(NewMarkbookDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_selectFileButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        //validate
        if(newMarkbookDialogBean.getMarkBookFile() == null){
            JOptionPane.showMessageDialog(this, "Markbook file must be selected", "Oops!", JOptionPane.WARNING_MESSAGE);   
            return;
        }
        if(! newMarkbookDialogBean.getMarkBookFile().exists() || newMarkbookDialogBean.getMarkBookFile().isDirectory()){
            JOptionPane.showMessageDialog(this, "Invalid Markbook file", "Oops!", JOptionPane.WARNING_MESSAGE);   
            return;            
        }
        if(StringUtils.isBlank(newMarkbookDialogBean.getMarkBookTitle())){
            JOptionPane.showMessageDialog(this, "Title required", "Oops!", JOptionPane.WARNING_MESSAGE);   
            return;                
        }
        if(StringUtils.isBlank(newMarkbookDialogBean.getCurriculumTitle())){
            JOptionPane.showMessageDialog(this, "Curriculum required", "Oops!", JOptionPane.WARNING_MESSAGE);   
            return;               
        }
        
        dialogResult.setElement(newMarkbookDialogBean);
        dialogResult.setResultType(DialogResult.ResultType.OK);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void canelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canelButtonActionPerformed
        dialogResult.setResultType(DialogResult.ResultType.CANCEL);
        this.dispose();
    }//GEN-LAST:event_canelButtonActionPerformed

    public DialogResult<NewMarkbookDialogBean> getDialogResult(){
        return dialogResult;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox markBookCurriculumComboBox;
    private javax.swing.JTextField markBookFilenameTextField;
    private javax.swing.JTextField markbookTitleTextField;
    private markbookreporterui.view.NewMarkbookDialogBean newMarkbookDialogBean;
    private javax.swing.JButton okButton;
    private javax.swing.JButton selectFileButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
